## makeCacheMatrix and cacheSolve are are a pair of functions that enable the
## caching and subsequent use of a cached matrix and its inverse. Both
## functions are derived from the samples provided by Roger Peng; i.e.,
## makeCacheMatrix is derived from makeVector and cacheSolve is derived from
## cachemean.

## makeCacheMatrix: takes a matrix and creates a special "matrix" object
## that caches both the matrix and its inverse for future use.
## NB: setinverse is primarily designed for use within cacheSolve; getinverse
## will not return an inverted matrix until the pseudo-matrix generated by
## makeCacheMatrix has been cacheSolve'd.
makeCacheMatrix <- function(x = matrix()) {
    ## create variable to store the inverted matrix
    m <- NULL

    ## create set/get functions for storing and retrieving the original matrix
    set <- function(y) {
        x <<- y
        m <<- NULL
    }
    get <- function() x
    
    ## create set/get functions for storing and retrieving the inverted matrix
    setinverse <- function(inverse) m <<- inverse
    getinverse <- function() m
    
    ## return a list with the four functions so they are available for use
    list(set = set, get = get,
         setinverse = setinverse,
         getinverse = getinverse)
}

## cacheSolve: computes the inverse of the special "matrix" returned by
## makeCacheMatrix. If the inverse has already been calculated (and the matrix
## has not changed), cacheSolve retrieves the inverse from the cache.
cacheSolve <- function(x, ...) {
    ## try to get the inverted matrix from the cache; if successful, return
    ## it and note that it came from the cache
    m <- x$getinverse()
    if(!is.null(m)) {
        message("getting cached data")
        return(m)
    }
    
    ## if the inverted matrix is not in the cache, get the original matrix,
    ## invert it, and cache it for future use
    data <- x$get()
    m <- solve(data, ...)
    x$setinverse(m)
    
    ## return the freshly inverted matrix
    m
}
